#!/usr/bin/perl
#
# File:        L1B3.pl
#
# Description: Process control script for the Level 1B Processor.
#
# Author:      Generated by JEB, for test3
#
# Date:        Nov 13
#

# Input Parameters

$ENV{"SWS_L1B_CONFIG_FILESPEC"} = "/u/polecat0/belz/rapidscat_science_data_processing/test3/app-res/QS_PC1B0003";
$ENV{"SWS_L1B_METACONFIG_FILESPEC"} = "/u/polecat0/belz/rapidscat_science_data_processing/test3/app-res/QS_MC1B0001";

## This is the money input: it is the L1A file from which L1B is derived
$ENV{"SWS_LEVEL_1A_FILESPEC"} = "/home/belz/rsdp/test3/L1A/data/QS_S1A70934.20133091059";


## ZERO forever
$ENV{"SWS_NUMBER_DATA_SKIPS"} = "0";

##  Figureing this out:
##  (1) Convert L1A to h5, open in h5, read in Range(Begining/Ending)(Data/Time) and get endpoints
##         2013-031 12:23:10.100          to    2013-031 14:04:08.362
##  (2)    Add/Subtract Granule Overlap Time from end points (120 s)
#>>>print dt.datetime(2013,1,31, 12, 23, 10, 100000) - dt.timedelta(0,120),
#>>>print dt.datetime(2013,1,31, 14, 4, 8, 362000) + dt.timedelta(0,120)
#
#        2013-01-31 12:21:10.100000           2013-01-31 14:06:08.362000          
#
# Now compare to headers from the L1A data
#
#/home/belz/rsdp/test3/INPUTS/gpsephm>head -21 QS_SEPHG20130310243.20130311006.le QS_SEPHG20130310921.20130311643.le QS_SEPHG20130311108.20130311835.le  | grep Range
#RangeBeginningDate            = 2013-031                                     ;
#RangeBeginningTime            = 02:43:38.320                                 ;
#RangeEndingDate               = 2013-031                                     ;
#RangeEndingTime               = 09:22:26.318                                 ;
#RangeBeginningDate            = 2013-031                                     ;
#RangeBeginningTime            = 09:21:56.318                                 ;
#RangeEndingDate               = 2013-031                                     ;
#RangeEndingTime               = 16:00:45.318                                 ;
#RangeBeginningDate            = 2013-031                                     ;
#RangeBeginningTime            = 11:08:10.318                                 START
#RangeEndingDate               = 2013-031                                     STOP
#RangeEndingTime               = 17:46:56.317    
#
##  (3) Count files that have data in range
##  (4) Put them here.



$ENV{"SWS_NUM_EPHEMERIS_FILES"} = "1";
# note: this matches pm's result
$ENV{"SWS_EPHEMERIS_FILESPEC_01"} = "INPUTS/gpsephm/QS_SEPHG20130311108.20130311835.le";


# I have no idea how PM got zero
$ENV{"SWS_NUM_ATTITUDE_FILES"} = "0";
#$ENV{"SWS_ATTITUDE_FILESPEC_01"} = "INPUTS/att/QS_SATT_20130311108.20130311835.le";


## Note sure, but I thnk we want the matching and adjacent rev numbers (PM did this)
$ENV{"SWS_NUM_CAL_PULSE_FILES"} = "3";
$ENV{"SWS_CAL_PULSE_FILESPEC_01"} = "/u/polecat0/belz/rapidscat_science_data_processing/test3/CALP/data/QS_SCAL70933.20133171010";
$ENV{"SWS_CAL_PULSE_FILESPEC_02"} = "/u/polecat0/belz/rapidscat_science_data_processing/test3/CALP/data/QS_SCAL70934.20133171010";
$ENV{"SWS_CAL_PULSE_FILESPEC_03"} = "/u/polecat0/belz/rapidscat_science_data_processing/test3/CALP/data/QS_SCAL70935.20133171010";

## Finde these tables in the "usual" tables constants -LE or not?
#$ENV{"SWS_DOPPLER_RANGE_DELAY_FILESPEC"} = "/u/polecat0/belz/rapidscat_science_data_processing/test2/tables/QS_DOPL0010";
$ENV{"SWS_DOPPLER_RANGE_DELAY_FILESPEC"} = "/home/rsdunbar/QS_DOPL0010.orig";

#$ENV{"SWS_L1B_CONSTANTS_FILESPEC"} = "/u/polecat0/belz/rapidscat_science_data_processing/test2/tables/QS_CN1B1013";                 # byte
#$ENV{"SWS_L1B_CONSTANTS_FILESPEC"} = "/u/polecat0/belz/rapidscat_science_data_processing/test2/tables/QS_CN1B1213";
#FIXIT!!!
$ENV{"SWS_L1B_CONSTANTS_FILESPEC"} = "/home/werne/QS_CN1B1213";                 # byte
$ENV{"SWS_TELEMETRY_CONSTANTS_FILESPEC"} = "/u/polecat0/belz/rapidscat_science_data_processing/test2/tables/QS_CNTM0019";           # nbyte
$ENV{"SWS_CAL_TEMPERATURE_FILESPEC"} = "/u/polecat0/belz/rapidscat_science_data_processing/test2/tables/QS_CTMP0002.le";            # byte
$ENV{"SWS_LEAP_SECOND_FILESPEC"} = "/u/polecat0/belz/rapidscat_science_data_processing/test2/tables/LEAP0004";                      # byte
$ENV{"SWS_GLOBAL_CONSTANTS_FILESPEC"} = "/u/polecat0/belz/rapidscat_science_data_processing/test2/tables/GLOB0003.le";              # byte

$ENV{"SWS_ANTENNA_PATTERN_FILESPEC"} = "/u/polecat0/belz/rapidscat_science_data_processing/test2/tables/QS_ANTP0001.le";           
$ENV{"SWS_BASEBAND_FREQ_CORR_FILESPEC"} = "/u/polecat0/belz/rapidscat_science_data_processing/test2/tables/QS_BFOC0003.le"; 

#FIXIT!!!
#$ENV{"SWS_EARTH_TOPO_MAP_FILESPEC"} = "/u/polecat0/belz/rapidscat_science_data_processing/test2/tables/TOPO0002.le";
$ENV{"SWS_EARTH_TOPO_MAP_FILESPEC"} = "/home/werne/TOPO0002.le";
$ENV{"SWS_KPC_PARAMETERS_FILESPEC"} = "/u/polecat0/belz/rapidscat_science_data_processing/test2/tables/QS_KPCP0001.le";
$ENV{"SWS_S_FACTOR_FILESPEC"} = "/u/polecat0/belz/rapidscat_science_data_processing/test2/tables/QS_SFAC0001.le";
$ENV{"SWS_SLICE_NOISE_FRACTION_FILESPEC"} = "/u/polecat0/belz/rapidscat_science_data_processing/test2/tables/QS_SNFR0001.le";       
$ENV{"SWS_X_FACTOR_FILESPEC"} = "/u/polecat0/belz/rapidscat_science_data_processing/test2/tables/QS_XFAC3007.le"; 


# Output Parameters


## OK, now we gotta mkdir before we run
$ENV{"SWS_LEVEL_1B_FILEPATH"} =  "./L1B/data2";
## make this to, but give it a respectable name
$ENV{"SWS_OUTPUT_REPORT_PATH"} = "./L1B/qarpt";
## Logging is TBD
$ENV{"SWS_ERRLOG_FILESPEC"} = "./echo2.log";
## THis is left over from L1A
$ENV{"SWS_STATUSLOG_PATH"} = "./app-logs/pm/meta";

# Processing Parameters

$ENV{"SWS_NUM_PARTS"} = "1";
$ENV{"SWS_ECHO_TRACK_FLAG"} = "2";
$ENV{"SWS_REV_GRANULE_OVERLAP_TIME"} = "120";
$ENV{"SWS_PROCESS_ENVIRONMENT"} = "SeaPAC";
$ENV{"SWS_PARAM_FILESPEC"} = $0;
## Is this the same as last time- meaning L1A?
#$ENV{"SWS_TASK_ID"} = "794212";
# copy value from PM
$ENV{"SWS_TASK_ID"} = "783811";

# Monitor Parameters

$ENV{"SWS_MON_SWS"} = "MON_L_OFF";
$ENV{"SWS_MON_L1B_LP"} = "MON_L_OFF";
$ENV{"SWS_MON_CONVERG"} = "MON_L_OFF";
$ENV{"SWS_MON_SIGMA0_AND_KP"} = "MON_L_OFF";
$ENV{"SWS_MON_CELL_GEOM"} = "MON_L_OFF";
$ENV{"SWS_MON_FRAME_PARAMS"} = "MON_L_OFF";
$ENV{"SWS_MON_ECHO_TRACK"} = "MON_L_OFF";

# PM Variables

$ENV{"PM_SERVER"} = "SPAC_INVENTORY";
$ENV{"PM_DB"} = "inventory";
$ENV{"PM_PMS"} = "PMSERVER";

# Call the executable to run the Level 1B Processor.

## gotta have it... better be a constant
$ENV{"SWS_ERRMSG_DIR"} = "/u/polecat0/belz/rapidscat_science_data_processing/test2/gen";

system ($ARGV[0] . " qs_lp_L1B") == 0
    or die "Level 1B Processor terminated";

