#!/usr/bin/perl
#
# File:        L1A2013032032024-783831.pl
#
# Description: Process control script for the Level 1A Processor.
#
# Author:      Generated by the pm_startAutoProc application.
#
# Date:        02/01/2013 03:20:24.000
#

# Input Parameters

$ENV{"SWS_L1A_CONFIG_FILESPEC"} = "/u/qscat/app-res/QS_PC1A0004";
$ENV{"SWS_L1A_METACONFIG_FILESPEC"} = "/u/qscat/app-res/QS_MC1A0001";

$ENV{"SWS_NUM_LEVEL_0_FILES"} = "2";
$ENV{"SWS_LEVEL_0_FILESPEC_01"} = "/seapac2/disk5/L00/data/QS_S0A20130311440.20130320013";
$ENV{"SWS_LEVEL_0_FILESPEC_02"} = "/seapac2/disk5/L00/data/QS_S0A20130311959.20130320316";

$ENV{"SWS_NUMBER_DATA_SKIPS"} = "0";

$ENV{"SWS_NUM_EPHEMERIS_FILES"} = "3";
$ENV{"SWS_EPHEMERIS_FILESPEC_01"} = "/calctbl/hk2/gpsephm/QS_SEPHG20130311108.20130311835";
$ENV{"SWS_EPHEMERIS_FILESPEC_02"} = "/calctbl/hk2/gpsephm/QS_SEPHG20130311627.20130320010";
$ENV{"SWS_EPHEMERIS_FILESPEC_03"} = "/calctbl/hk2/gpsephm/QS_SEPHG20130311959.20130320302";

$ENV{"SWS_NUM_ATTITUDE_FILES"} = "3";
$ENV{"SWS_ATTITUDE_FILESPEC_01"} = "/calctbl/hk2/att/QS_SATT_20130311108.20130311835";
$ENV{"SWS_ATTITUDE_FILESPEC_02"} = "/calctbl/hk2/att/QS_SATT_20130311627.20130320010";
$ENV{"SWS_ATTITUDE_FILESPEC_03"} = "/calctbl/hk2/att/QS_SATT_20130311959.20130320302";

$ENV{"SWS_TELEMETRY_CONSTANTS_FILESPEC"} = "/stt-tables/QS_CNTM0019";
$ENV{"SWS_CALIBRATION_MODE_MAP_FILESPEC"} = "/stt-tables/QS_CALM0001";
$ENV{"SWS_DN_EU_CONVERSION_FILESPEC"} = "/stt-tables/QS_DNEU0005";
$ENV{"SWS_LEAP_SECOND_FILESPEC"} = "/stt-tables/LEAP0004";
$ENV{"SWS_TIME_CONVERSION_DATA_FILESPEC"} = "/calctbl/hk2/time/QS_SCLK_UTC";
$ENV{"SWS_GLOBAL_CONSTANTS_FILESPEC"} = "/stt-tables/GLOB0003";

# Output Parameters

$ENV{"SWS_LEVEL_1A_FILEPATH"} = "/seapac2/disk5/L1A/data";
$ENV{"SWS_OUTPUT_REPORT_PATH"} = "/seapac2/disk5/L1A/qarpt";
$ENV{"SWS_CAL_PULSE_FILEPATH"} = "/seapac2/disk5/CALP/data";
$ENV{"SWS_STATUSLOG_PATH"} = "/u/qscat/app-logs/pm/meta";
$ENV{"SWS_ERRLOG_FILESPEC"} = "/seapac2/disk5/L1A/log/L1A2013032032024-783831.log";

# Processing Parameters

$ENV{"SWS_LEVEL_1A_EXTENT"} = "1";
$ENV{"SWS_REV_GRANULE_OVERLAP_TIME"} = "120";
$ENV{"SWS_FIRST_REV_NUMBER"} = "70937";
$ENV{"SWS_FIRST_REV_TIME"} = "";
$ENV{"SWS_BEGIN_TIME_SPAN"} = "2013-031T16:00:00.000";
$ENV{"SWS_LENGTH_TIME_SPAN"} = "28800";
$ENV{"SWS_PROCESS_ENVIRONMENT"} = "SeaPAC";
$ENV{"SWS_PARAM_FILESPEC"} = $0;
$ENV{"SWS_TASK_ID"} = "783831";

# Monitor Parameters

$ENV{"SWS_MON_SWS"} = "MON_L_OFF";
$ENV{"SWS_MON_L1A_LP"} = "MON_L_OFF";
$ENV{"SWS_MON_CAL_PULSE"} = "MON_L_OFF";
$ENV{"SWS_MON_INTERP_TELEM"} = "MON_L_OFF";
$ENV{"SWS_MON_PROC_TELEM"} = "MON_L_OFF";

# PM Variables

$ENV{"PM_SERVER"} = "SPAC_INVENTORY";
$ENV{"PM_DB"} = "inventory";
$ENV{"PM_PMS"} = "PMSERVER";

# Call the executable to run the Level 1A Processor.

$ENV{"SWS_ERRMSG_DIR"} = "/u/qscat/app-res/gen";

system ("/u/qscat/bin/sparc/qs_lp_1A") == 0
    or die "Level 1A Processor terminated";

