#!/usr/bin/perl
#
# File:        L2B2013032005011-783808.pl
#
# Description: Process control script for the Level 2B Processor.
#
# Author:      Generated by the pm_spacOps application.
#
# Date:        02/01/2013 00:50:11.000
#

# Input Parameters

$ENV{"SWS_L2B_CONFIG_FILESPEC"} = "/u/qscat/app-res/QS_PC2B0006.CP12";
$ENV{"SWS_L2B_METACONFIG_FILESPEC"} = "/u/qscat/app-res/QS_MC2B0001";
$ENV{"SWS_LEVEL_2A_FILESPEC"} = "/seapac2/disk5/L2A/data/QS_S2A70931.20130311915.CP12";
$ENV{"SWS_25KM_LEVEL_2B_FILESPEC"} = "/seapac2/disk5/L2B/data/QS_S2B70931.20130311919";
$ENV{"SWS_WEATHER_DATA_FILESPEC"} = "/calctbl/nwp1/data/SNWP1201303106";
$ENV{"SWS_RAIN_CLASSIFICATION_FILESPEC"} = "/stt-tables/QS_MRCL1130.CP12";
$ENV{"SWS_EXP_MEAN_OBJ_FUNC_FILESPEC"} = "/stt-tables/QS_EMOF0001.CP12";
$ENV{"SWS_GEOPHYSICAL_MODEL_FUNCTION_FILESPEC"} = "/stt-tables/QS_MODLa004";
$ENV{"SWS_OCEAN_BACKGROUND_TB_FILESPEC"} = "/stt-tables/QS_OBTB0001";
$ENV{"SWS_L2B_CONSTANTS_FILESPEC"} = "/stt-tables/QS_CN2B1130.CP12";
$ENV{"SWS_GLOBAL_CONSTANTS_FILESPEC"} = "/stt-tables/GLOB0003";
$ENV{"SWS_SKILL_COEFF_TABLE"} = "/stt-tables/QS_SKIL0101.CP12";

# Output Parameters

$ENV{"SWS_LEVEL_2B_FILEPATH"} = "/seapac2/disk5/L2B/data";
$ENV{"SWS_OUTPUT_REPORT_PATH"} = "/seapac2/disk5/L2B/qarpt";
$ENV{"SWS_STATUSLOG_PATH"} = "/u/qscat/app-logs/pm/meta";
$ENV{"SWS_ERRLOG_FILESPEC"} = "/seapac2/disk5/L2B/log/L2B2013032005011-783808.log";

# Processing Parameters

$ENV{"SWS_NUM_PARTS"} = "1";
$ENV{"SWS_WVC_ROW_OVERLAP"} = "156";
$ENV{"SWS_L2B_MODULUS"} = "1";
$ENV{"SWS_SIN_MODULUS"} = "1";
$ENV{"SWS_NUDGE_FLAG"} = "3";
$ENV{"SWS_ATTN_FLAG"} = "2";
$ENV{"SWS_DIRECTION_RETRIEVAL_ENHANCEMENT"} = "1";
$ENV{"SWS_AMBIG_REMOVAL_METHOD"} = "1";
$ENV{"SWS_PARAM_FILESPEC"} = $0;
$ENV{"SWS_TASK_ID"} = "783808";

# Monitor Parameters

$ENV{"SWS_MON_SWS"} = "MON_L_OFF";
$ENV{"SWS_MON_L2B_LP"} = "MON_L_OFF";
$ENV{"SWS_MON_PREPARE_WVC"} = "MON_L_OFF";
$ENV{"SWS_MON_RETRIEVE_WINDS"} = "MON_L_OFF";
$ENV{"SWS_MON_REMOVE_AMBIG"} = "MON_L_OFF";

# PM Variables

$ENV{"PM_SERVER"} = "SPAC_INVENTORY";
$ENV{"PM_DB"} = "inventory";
$ENV{"PM_PMS"} = "PMSERVER";

# Call the executable to run the Level 2B Processor.

$ENV{"SWS_ERRMSG_DIR"} = "/u/qscat/app-res/gen";

system ("/u/qscat/bin/sparc/qs_lp_2B") == 0
    or die "Level 2B Processor terminated";

