//==========================================================//
// Copyright (C) 1997, California Institute of Technology.	//
// U.S. Government sponsorship acknowledged.				//
//==========================================================//

//----------------------------------------------------------------------
// NAME
//		l15_to_kpr_table
//
// SYNOPSIS
//		l15_to_kpr_table <noisefree_l15_file> <noisy_l15_file> <output_file>
//
// DESCRIPTION
//              Calculates kpr as a function of azimuth, slice_number,
//		and beam_number (inner=0 or outer=1).
//
// OPTIONS
//		None.
//
// OPERANDS
//		The following operand is supported:
//		<noisefree_l15_file>	A level 1.5 file which contains data
//                                      generated by assuming the radar
//                                      parameters X are noisefree and the
//                                      power received is noisefree.
//
//              <noisy_l15_file>        Data generated in exactly the same 
//                                      manner as the previous file but
//                                      with noise added to X in some
//                                      manner. (Attitude knowledge error, etc)
//
//              <output_file>           Kpr output file, Binary Format:
//                                      int number_of_beams
//                                      float sliceBandWidth
//                                      int slicesPerSpot
//                                      int number_of_azimuth_bins
//                                      kpr[beam#][slice#][azimuth#] 
//  
//
// EXAMPLES
//		An example of a command line is:
//			% l15_to_kprtable quiet_l15.dat noisy.l15.dat out.kpr
//
// ENVIRONMENT
//		Not environment dependent.
//
// EXIT STATUS
//		The following exit values are returned:
//		0	Program executed successfully
//		>0	Program had an error
//
// NOTES
//		None.
//
// AUTHOR
//		Bryan W. Stiles
//		bstiles@warukaze.jpl.nasa.gov
//----------------------------------------------------------------------


//-----------------------//
// Configuration Control //
//-----------------------//

static const char rcs_id[] =
	"@(#) $Id$";

//----------------------//
// Includes             //
//----------------------//

#include<stdio.h>
#include<math.h>
#include "List.h"
#include "List.C"
#include "BufferedList.h"
#include "BufferedList.C"
#include "Kpr.h"
#include "Meas.h"
#include "L1b.h"
#include "Misc.h"

//-----------------------//
// Templates             //
//-----------------------//

template class List<Meas>;
template class List<EarthPosition>;
template class List<MeasSpot>;
template class BufferedList<OrbitState>;
template class List<OrbitState>;
template class List<long>;
template class List<OffsetList>;

//-----------//
// CONSTANTS //
//-----------//

#define NUMBER_OF_AZIMUTH_BINS 50
#define NUM_SCIENCE_SLICES 10
#define NUM_GUARD_SLICES_EACH_SIDE 1
#define NUMBER_OF_BEAMS 2
#define SLICE_BANDWIDTH 8314.0
#define MIN_NUM_SAMPLES 10
#define FILTER_SIZE 3
#define FILTER_NUM_PASSES 2

//------------------//
// GLOBAL VARIABLES //
//------------------//

const char* usage_array[] = { "<noisefree_l15_file>", "<noisy_l15_file>",
			      "<output_file>",0};

int main(int argc, char* argv[]){	

        //------------------------//
        // parse the command line //
	//------------------------//

	const char* command = no_path(argv[0]);
	if (argc != 4)
		usage(command, usage_array, 1);

	//--------------------------------------//
	// create and configure L15 products    //
	//--------------------------------------//

	L15 noisy, noisefree;

	noisefree.SetFilename(argv[1]);
	noisy.SetFilename(argv[2]);


	//-------------------------------------//
	// Create KprTable                     //
	//-------------------------------------//

	Kprs kpr(NUMBER_OF_BEAMS,SLICE_BANDWIDTH,SLICE_BANDWIDTH,
		 NUM_SCIENCE_SLICES, NUM_GUARD_SLICES_EACH_SIDE,
		     NUMBER_OF_AZIMUTH_BINS, MIN_NUM_SAMPLES);

	//------------//
	// open files //
	//------------//

	noisefree.OpenForReading();
	noisy.OpenForReading();
	
	do{
		//------------------------------//
		// read level 1.5 data records  //
		//------------------------------//

		if (! noisefree.ReadDataRec())
		{
			switch (noisefree.GetStatus())
			{
			case L15::OK:	// end of file
				break;
			case L15::ERROR_READING_FRAME:
				fprintf(stderr, "%s: error reading Level 1.5 data\n", command);
				exit(1);
				break;
			case L15::ERROR_UNKNOWN:
				fprintf(stderr, "%s: unknown error reading Level 1.5 data\n",
					command);
				exit(1);
				break;
			default:
				fprintf(stderr, "%s: unknown status (???)\n", command);
				exit(1);
			}
			break;	// done, exit do loop
		}		

		//------------------------------//
		// read a level 1.5 data record //
		//------------------------------//

		if (! noisy.ReadDataRec())
		{
			switch (noisy.GetStatus())
			{
			case L15::OK:	// end of file
				break;
			case L15::ERROR_READING_FRAME:
				fprintf(stderr, "%s: error reading Level 1.5 data\n", command);
				exit(1);
				break;
			case L15::ERROR_UNKNOWN:
				fprintf(stderr, "%s: unknown error reading Level 1.5 data\n",
					command);
				exit(1);
				break;
			default:
				fprintf(stderr, "%s: unknown status (???)\n", command);
				exit(1);
			}
			break;	// done, exit do loop
		}

		if(! kpr.Accumulate(&(noisefree.frame.spotList),
				    &(noisy.frame.spotList)))
		  {
		    fprintf(stderr, "%s: Accumulating of kpr values failed\n",
			    command);
		    exit(1);
		  }
	}while(1);
	if (!kpr.Normalize()){
	  fprintf(stderr, "%s: Normalization of kpr values failed\n",command);
	  exit(1);
	}
        for(int c=0;c < FILTER_NUM_PASSES; c++){
	  if (!kpr.Smooth(FILTER_SIZE)){
	    fprintf(stderr, "%s: Smoothing of kpr values failed\n",command);
	    exit(1);
	  }

	}
	if (!kpr.Write(argv[3])){
	  fprintf(stderr, "%s: Unable to write kpr table to file\n",command);
	  exit(1);
	}
	exit(0);
}

