#include<stdio.h>
#include<stdlib.h>
#include"Constants.h"
#include"MLP.h"
#include"MLPData.h"

// Routine for converting Cassini or AmbigSim style beam patterns to
// OVWM style patterns
int main(int argc, char* argv[]){
  if(argc!=5){
    fprintf(stderr,"Usage:%s testfile netfile latlonfile outfile\n",argv[0]);
    exit(1);
  }
  int clidx=1;
  char* testfile = argv[clidx++];
  char* netfile = argv[clidx++];
  char* latlonfile = argv[clidx++];
  char* outfile = argv[clidx++];
  MLPData data;
  if(!data.Read(testfile)){
    fprintf(stderr,"Unable to read testfile %s\n",testfile);
    exit(1);
  }
  MLPData results;
  results.num_samps=data.num_samps;
  results.num_inpts=data.num_outpts;
  results.num_outpts=data.num_outpts;
  results.Allocate();
  MLP mlp;
  if(!mlp.Read(netfile)){
    fprintf(stderr,"Unable to read netfile %s\n",netfile);
    exit(1);
  }

  float mse=mlp.Test(&data,&results);
  printf("MSE= %g RMS=%g\n",mse,sqrt(mse));

  /* read latlon file to get lat and lon values */
  /* A script should create the latlon and data files from the outputs
     of l2a_to_l2b */
  /* for now we will use spddat files for input and output ***/
  /* and data files generated by MATLAB **/

  int nsamps;

  FILE* ifp=fopen(latlonfile,"r");
  if(ifp==NULL){
    fprintf(stderr,"Unable to open latlonfile file %s\n",latlonfile);
    exit(1);
  }
  if(fread(&nsamps,sizeof(int),1,ifp)!=1)
    {
      fprintf(stderr,"Error reading header from latlonfile %s\n",latlonfile);
      exit(1);
    }
  if(nsamps!=results.num_samps){
    fprintf(stderr,"Number of samples mismatch between latlonfile and test data file\n");
    exit(1);
  }
  float* lat=(float*)malloc(sizeof(float)*nsamps);
  float* lon=(float*)malloc(sizeof(float)*nsamps);
  float* spd=(float*)malloc(sizeof(float)*nsamps);
  if(fread(lat,sizeof(int),nsamps,ifp)!=(unsigned int) nsamps ||  
     fread(lon,sizeof(int),nsamps,ifp)!=(unsigned int) nsamps){
      fprintf(stderr,"Error reading data from latlonfile %s\n",latlonfile);
      exit(1);
  }
  fclose(ifp);
  for(int c=0;c<nsamps;c++) spd[c]=results.inpt[c][0];
  
  /* write spddat file */

  FILE* ofp=fopen(outfile,"w");
  if(ifp==NULL){
    fprintf(stderr,"Unable to create output file %s\n",outfile);
    exit(1);
  }
  if(fwrite(&nsamps,sizeof(int),1,ofp)!=1)
    {
      fprintf(stderr,"Error writing header to outfile %s\n", outfile);
      exit(1);
    }
  if(fwrite(lat,sizeof(int),nsamps,ofp)!=(unsigned int) nsamps ||  
     fwrite(lon,sizeof(int),nsamps,ofp)!=(unsigned int) nsamps ||
     fwrite(spd,sizeof(int),nsamps,ofp)!=(unsigned int) nsamps){
      fprintf(stderr,"Error writing data to outfile %s\n",outfile);
      exit(1);
  }
  fclose(ofp);
  free(spd);
  free(lat);
  free(lon);
  return(0);
}
